# Generated by Django 3.2.7 on 2021-09-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='従業員名/苗字')),
                ('first_name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='従業員名/名前')),
                ('last_name_kana', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='従業員名/苗字/ひらがな')),
                ('first_name_kana', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='従業員名/名前/ひらがな')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=1, null=True, verbose_name='性別')),
            ],
        ),
    ]
